<SplashScreen>:

MDScreen:
    
    name: "splashScreen"
    
    MDBoxLayout:
        
        orientation: 'vertical'
        MDFloatLayout:

            Video:
                source:'Images/Intro.mp4'
                state: 'play'
                options: {'eos': 'stop'}
                allow_stretch: True
                keep_ratio: False
                size_hint: (1, 1)
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            


          